# Koh-I-Noor Polycolor 72 - kolory w kolejności tonalno-kolorystycznej
# Źródło prawdy: ZESTAW_72_KOLOROW.txt

COLORS_72 = [
    (1, "Titanium White"),
    (500, "Ivory Bone"),
    (41, "Banana Yellow"),
    (2, "Lemon Yellow"),
    (43, "Pollen Yellow"),
    (44, "Naples Yellow"),
    (3, "Chrome Yellow"),
    (4, "Dark Yellow Ochre"),
    (67, "Persian Orange"),
    (9, "Apricot Orange"),
    (45, "Light Orange"),
    (5, "Reddish Orange"),
    (42, "Chromium Orange"),
    (46, "Fire Orange"),
    (10, "French Pink"),
    (6, "Vermilion Red"),
    (47, "Scarlet Red"),
    (48, "Dark Vermilion Red"),
    (7, "Carmine Red"),
    (8, "Bordeaux Red"),
    (76, "Pyrrole Red"),
    (11, "Lavender Violet"),
    (12, "Reddish Violet"),
    (50, "Windsor Violet"),
    (51, "Dark Violet"),
    (14, "Bluish Violet"),
    (15, "Ice Blue"),
    (18, "Light Blue"),
    (16, "Cerulean Blue"),
    (52, "Dark Ice Blue"),
    (57, "Mountain Blue"),
    (17, "Cobalt Blue"),
    (54, "Dark Cobalt Blue"),
    (53, "Phthalo Blue"),
    (55, "Permanent Blue"),
    (19, "Sapphire Blue"),
    (56, "Indigo Blue"),
    (20, "Prussian Blue"),
    (22, "Yellowish Green"),
    (23, "Spring Green"),
    (58, "Light Green"),
    (62, "Apple Green"),
    (24, "Pea Green"),
    (59, "Grass Green"),
    (25, "Meadow Green"),
    (60, "Emerald Green"),
    (61, "Sap Green"),
    (21, "Bluish Green"),
    (63, "Light Olive Green"),
    (27, "Dark Olive Green"),
    (26, "Dark Green"),
    (29, "Light Ochre"),
    (28, "Gold Ochre"),
    (801, "Yellow Ochre"),
    (64, "Burnt Ochre"),
    (30, "Reddish Brown"),
    (31, "Light Brown"),
    (65, "Medium Terracotta"),
    (32, "Natural Sienna"),
    (66, "Raw Umber"),
    (68, "Burnt Umber"),
    (33, "Dark Brown"),
    (69, "Cool Grey 1"),
    (403, "Cool Grey 3"),
    (71, "Medium Grey"),
    (70, "Cool Grey 9"),
    (72, "Slate Grey"),
    (34, "Light Bluish Grey"),
    (38, "Cool Grey 8"),
    (39, "Standard Silver"),
    (40, "Standard Gold"),
    (36, "Ivory Black"),
]
