# -*- coding: utf-8 -*-
"""
Mój zestaw 72 kolorów Koh-I-Noor Polycolor - kolejność tonalna
Kolejność zgodna z katalogiem 144
"""

COLORS_MY_72 = [
    (1, "Titanium White"),
    (41, "Banana Yellow"),
    (504, "Lemon Yellow"),
    (3, "Chrome Yellow"),
    (801, "Yellow Ochre"),
    (28, "Gold Ochre"),
    (45, "Light Orange"),
    (44, "Naples Yellow"),
    (42, "Chromium Orange"),
    (558, "Fire Orange"),
    (126, "Persian Orange"),
    (5, "Reddish Orange"),
    (6, "Vermilion Red"),
    (170, "Pyrrole Red"),
    (601, "Scarlet Red"),
    (132, "Carmine Red"),
    (603, "Wine Red"),
    (131, "French Pink"),
    (357, "Apricot Orange"),
    (178, "Reddish Violet"),
    (177, "Lilac Violet"),
    (8, "Bordeaux Red"),
    (182, "Dark Violet"),
    (180, "Dark Lavender Violet"),
    (13, "Lavender Violet"),
    (179, "Bluish Violet"),
    (181, "Windsor Violet"),
    (17, "Cobalt Blue"),
    (56, "Indigo Blue"),
    (55, "Permanent Blue"),
    (19, "Sapphire Blue"),
    (54, "Dark Cobalt Blue"),
    (53, "Phthalo Blue"),
    (52, "Dark Ice Blue"),
    (18, "Light Blue"),
    (20, "Prussian Blue"),
    (57, "Mountain Blue"),
    (16, "Cerulean Blue"),
    (15, "Ice Blue"),
    (26, "Dark Green"),
    (61, "Sap Green"),
    (59, "Grass Green"),
    (60, "Emerald Green"),
    (21, "Bluish Green"),
    (24, "Pea Green"),
    (58, "Light Green"),
    (23, "Spring Green"),
    (22, "Yellowish Green"),
    (62, "Apple Green"),
    (25, "Meadow Green"),
    (63, "Light Olive Green"),
    (27, "Dark Olive Green"),
    (66, "Raw Umber"),
    (802, "Dark Yellow Ochre"),
    (29, "Light Ochre"),
    (64, "Burnt Ochre"),
    (30, "Reddish Brown"),
    (65, "Medium Terracotta"),
    (31, "Light Brown"),
    (32, "Natural Sienna"),
    (33, "Dark Brown"),
    (68, "Burnt Umber"),
    (40, "Standard Gold"),
    (39, "Standard Silver"),
    (34, "Light Bluish Grey"),
    (72, "Slate Grey"),
    (71, "Medium Grey"),
    (408, "Cool Grey 8"),
    (406, "Cool Grey 6"),
    (403, "Cool Grey 3"),
    (401, "Cool Grey 1"),
    (36, "Ivory Black"),
]