# Koh-I-Noor Polycolor 72 - kolory w kolejności katalogowej
# Źródło prawdy: ZESTAW_72_KOLOROW.txt

COLORS_72_CATALOG = [
    (500, "Ivory Bone"),
    (43, "Pollen Yellow"),
    (41, "Banana Yellow"),
    (2, "Lemon Yellow"),
    (3, "Chrome Yellow"),
    (801, "Yellow Ochre"),
    (28, "Gold Ochre"),
    (45, "Light Orange"),
    (44, "Naples Yellow"),
    (42, "Chromium Orange"),
    (46, "Fire Orange"),
    (67, "Persian Orange"),
    (5, "Reddish Orange"),
    (6, "Vermilion Red"),
    (76, "Pyrrole Red"),
    (48, "Dark Vermilion Red"),
    (47, "Scarlet Red"),
    (7, "Carmine Red"),
    (10, "French Pink"),
    (9, "Apricot Orange"),
    (12, "Reddish Violet"),
    (8, "Bordeaux Red"),
    (51, "Dark Violet"),
    (11, "Lavender Violet"),
    (14, "Bluish Violet"),
    (50, "Windsor Violet"),
    (17, "Cobalt Blue"),
    (56, "Indigo Blue"),
    (55, "Permanent Blue"),
    (19, "Sapphire Blue"),
    (54, "Dark Cobalt Blue"),
    (53, "Phthalo Blue"),
    (52, "Dark Ice Blue"),
    (18, "Light Blue"),
    (20, "Prussian Blue"),
    (57, "Mountain Blue"),
    (16, "Cerulean Blue"),
    (15, "Ice Blue"),
    (26, "Dark Green"),
    (61, "Sap Green"),
    (59, "Grass Green"),
    (60, "Emerald Green"),
    (21, "Bluish Green"),
    (24, "Pea Green"),
    (58, "Light Green"),
    (23, "Spring Green"),
    (22, "Yellowish Green"),
    (62, "Apple Green"),
    (25, "Meadow Green"),
    (63, "Light Olive Green"),
    (27, "Dark Olive Green"),
    (66, "Raw Umber"),
    (4, "Dark Yellow Ochre"),
    (29, "Light Ochre"),
    (64, "Burnt Ochre"),
    (30, "Reddish Brown"),
    (65, "Medium Terracotta"),
    (31, "Light Brown"),
    (32, "Natural Sienna"),
    (33, "Dark Brown"),
    (68, "Burnt Umber"),
    (40, "Standard Gold"),
    (39, "Standard Silver"),
    (34, "Light Bluish Grey"),
    (72, "Slate Grey"),
    (71, "Medium Grey"),
    (38, "Cool Grey 8"),
    (403, "Cool Grey 3"),
    (69, "Cool Grey 1"),
    (36, "Ivory Black"),
    (70, "Cool Grey 9"),
    (1, "Titanium White"),
]
