# -*- coding: utf-8 -*-
"""
Zestaw 72 kolorów Koh-I-Noor Polycolor - KATALOG 2017
Kolejność zgodna z katalogiem z 2017 roku
Numery z katalogu 2017, nazwy z katalogu 144 (jeśli dostępne)
"""

COLORS_72_2017 = [
    (1, "Titanium White"),
    (41, "Banana Yellow"),
    (2, "Light Yellow"),
    (3, "Chrome Yellow"),
    (4, "Dark Yellow"),
    (43, "Canary Yellow"),
    (44, "Naples Yellow"),
    (9, "Beige"),
    (45, "Light Orange"),
    (67, "Cadmium Orange"),
    (126, "Persian Orange"),
    (42, "Chromium Orange"),
    (5, "Reddish Orange"),
    (47, "Scarlet Red"),
    (132, "Carmine Red"),
    (6, "Vermilion Red"),
    (48, "Carmine Red"),
    (30, "Reddish Brown"),
    (170, "Pyrrole Red"),
    (8, "Bordeaux Red"),
    (131, "French Pink"),
    (177, "Lilac Violet"),
    (178, "Reddish Violet"),
    (13, "Lavender Violet"),
    (180, "Dark Lavender Violet"),
    (179, "Bluish Violet"),
    (181, "Windsor Violet"),
    (182, "Dark Violet"),
    (57, "Mountain Blue"),
    (15, "Ice Blue"),
    (16, "Cerulean Blue"),
    (52, "Dark Ice Blue"),
    (53, "Phthalo Blue"),
    (18, "Light Blue"),
    (54, "Dark Cobalt Blue"),
    (17, "Cobalt Blue"),
    (19, "Sapphire Blue"),
    (55, "Permanent Blue"),
    (20, "Prussian Blue"),
    (56, "Indigo Blue"),
    (22, "Yellowish Green"),
    (62, "Apple Green"),
    (58, "Light Green"),
    (23, "Spring Green"),
    (24, "Pea Green"),
    (25, "Meadow Green"),
    (61, "Sap Green"),
    (59, "Grass Green"),
    (60, "Emerald Green"),
    (21, "Bluish Green"),
    (26, "Dark Green"),
    (63, "Light Olive Green"),
    (27, "Dark Olive Green"),
    (28, "Gold Ochre"),
    (29, "Light Ochre"),
    (66, "Raw Umber"),
    (64, "Burnt Ochre"),
    (32, "Natural Sienna"),
    (31, "Light Brown"),
    (65, "Medium Terracotta"),
    (33, "Dark Brown"),
    (68, "Burnt Umber"),
    (69, "Light Grey"),
    (35, "Grey"),
    (34, "Light Bluish Grey"),
    (71, "Medium Grey"),
    (72, "Slate Grey"),
    (38, "Cold Grey"),
    (70, "Dark Grey"),
    (36, "Ivory Black"),
    (39, "Standard Silver"),
    (40, "Standard Gold"),
]